name: olx_for_iitrpr
description: A new Flutter project.

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.5.2
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.2
  intl: ^0.18.0
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  characters: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
